---
name: ansible-deploy
on:
  push:
    branches: [ master, staging ]
jobs:
  job-1:
    runs-on: [self-hosted, runner-ansible-deploy]
    steps:
      - name: Say Hello
        run: echo "Hello"
  job-2:
    runs-on: [self-hosted, runner-ansible-deploy]
    steps:
      - name: Say World
        run: echo "World"
  slack-workflow-status:
    if: always()
    name: Post Workflow Status To Slack
    needs:
      - job-1
      - job-2
    runs-on: [self-hosted, runner-ansible-deploy]
    steps:
      - name: Slack Workflow Notification
        uses: slackapi/slack-github-action@v1.22.0
        with:
          # Required Input
          slack_webhook_url: ${{secrets.SLACK_WEBHOOK_URL}}
          # Optional Input
          channel: '#jenkins-cac'
          slack-message: "Github Action Build Number ${{ github.run_number }} failed for ${{ github.repository }} and the outcome is  ${{ needs.ansible-deploy.result }}."
          name: 'test'
