---
name: ansible-deploy

on:
  push:
    branches:
      - main
    paths-ignore:
      - ".elastic_runner/**"
      - ".github/**"
      - ".gitignore"
      - ".pre-commit-config.yaml"
      - ".vscode/**"
      - ".yamllint.yml"
      - "**.md"
      - "playbooks/**"
  schedule:
    # The time chosen is just arbitrary and randomly generated
    - cron: 0 8 * * *
  workflow_dispatch:
    inputs:
      ansible_tags:
        description: Features to pass on to Ansible
        default: all
        required: false
      ansible_host_limit:
        description: Hosts to pass on to Ansible
        default: all
        required: false
jobs:
  job-1:
    runs-on: [self-hosted, runner-ansible-deploy]
    steps:
      - name: Say Hello
        run: echo "Hello"
  job-2:
    runs-on: [self-hosted, runner-ansible-deploy]
    steps:
      - name: Say World
        run: echo "test"
  slack-workflow-status:
    if: always()
    name: Post Workflow Status To Slack
    needs:
      - job-1
      - job-2
    runs-on: [self-hosted, runner-ansible-deploy]
    steps:
      - name: Slack Workflow Notification
        uses: slackapi/slack-github-action@v1.22.0
        with:
          # Required Input
          slack_webhook_url: ${{secrets.SLACK_WEBHOOK_URL}}
          # Optional Input
          channel: '#jenkins-cac'
          slack-message: "Github Action Build Number ${{ github.run_number }} failed for ${{ github.repository }} and the outcome is  ${{ needs.ansible-deploy.result }}."
          name: 'test'
