---
name: ansible-deploy

on:
  push:
    branches:
      - main
    paths-ignore:
      - ".elastic_runner/**"
      - ".github/**"
      - ".gitignore"
      - ".pre-commit-config.yaml"
      - ".vscode/**"
      - ".yamllint.yml"
      - "**.md"
      - "playbooks/**"
  schedule:
    # The time chosen is just arbitrary and randomly generated
    - cron: 0 8 * * *
  workflow_dispatch:
    inputs:
      ansible_tags:
        description: Features to pass on to Ansible
        default: all
        required: false
      ansible_host_limit:
        description: Hosts to pass on to Ansible
        default: all
        required: false

jobs:
  ansible-deploy:
    runs-on: [self-hosted, runner-ansible-deploy]
    # env:
    #   ARTIFACT_PATH: /home/runner/_work/jenkins-cac/jenkins-cac/ansible-deploy.log
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v2

      - name: Setup python
        run: pip install -r requirements.txt

      - name: Ansible Deploy
        id: ansible-deploy
        env:
          BEFORE_SHA: ${{ github.event.before }}
          BUILD_REF: ${{ github.ref }}
          JENKINS_USERNAME: ${{ secrets.JENKINS_USERNAME }}
          JENKINS_PASSWORD: ${{ secrets.JENKINS_PASSWORD }}
          ANSIBLE_VAULT_PASSWORD: ${{ secrets.ANSIBLE_VAULT_PASSWORD }}
          EVENT_NAME: ${{ github.event_name }}
          INPUT_ANSIBLE_TAGS: ${{ github.event.inputs.ansible_tags }}
          INPUT_ANSIBLE_HOST_LIMIT: ${{ github.event.inputs.ansible_host_limit }}
          #RUN_ATTEMPT: ${{ github.run_attempt }}
        run: .github/workflows/scripts/ansible-deploy.sh ##| tee ansible-deploy.log

  notify:
    runs-on: [self-hosted, runner-ansible-deploy]
    if: failure()
    needs: ansible-deploy
    steps:
      - name: Send Slack notification when Github Actions fails
        id: slack
        uses: slackapi/slack-github-action@v1.21.0
        with:
          channel-id: "#jenkins-cac"
          slack-message: "Github Action Build Number ${{ github.run_number }} failed for ${{ github.repository }} and the outcome is  ${{ needs.ansible-deploy.result }}."
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
