---
name: ansible-deploy

on:
  push:
    branches:
      - main
    paths-ignore:
      - ".elastic_runner/**"
      - ".github/**"
      - ".gitignore"
      - ".pre-commit-config.yaml"
      - ".vscode/**"
      - ".yamllint.yml"
      - "**.md"
      - "playbooks/**"
  schedule:
    # The time chosen is just arbitrary and randomly generated
    - cron: 0 8 * * *
  workflow_dispatch:
    inputs:
      ansible_tags:
        description: Features to pass on to Ansible
        default: all
        required: false
      ansible_host_limit:
        description: Hosts to pass on to Ansible
        default: all
        required: false
jobs:
  job-1:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: echo "Hello"
  job-2:
    runs-on: ubuntu-latest
    steps:
      - name: Say World
        run: echo "test"
  slack-workflow-status:
    if: always()
    name: Post Workflow Status To Slack
    needs:
      - job-1
      - job-2
    runs-on: ubuntu-latest
    steps:
    - name: Send GitHub trigger payload to Slack Workflow Builder
      id: slack
      uses: slackapi/slack-github-action@v1.22.0
      with:
        payload: |
          {
            "text": "GitHub Action build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}",
            "blocks": [
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "GitHub Action build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
                }
              }
             ]
            }
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK

